import { WorkflowRegistry } from '../workflow.registry';

WorkflowRegistry.register({
  id: 'blog-post',
  name: 'Blog Post Writing',
  description: 'Strategize, research, SEO, write, review, compliance-check, publish, and distribute a blog post',
  version: '1.1.0',
  category: 'content',
  estimatedDurationMinutes: 25,
  tags: ['blog', 'writing', 'seo', 'content'],
  defaultInput: {
    tone: 'professional',
    contentType: 'blog',
  },
  steps: [
    {
      id: 'strategist',
      employeeType: 'strategist',
      title: 'Choose angle & keywords',
      description: 'Detect trends and pick a high-opportunity topic angle and target audience',
      dependsOn: [],
      approvalRequired: false,
      optional: true,
    },
    {
      id: 'research',
      employeeType: 'research',
      title: 'Research topic',
      description: 'Gather information, statistics, and references',
      dependsOn: ['strategist'],
      approvalRequired: false,
    },
    {
      id: 'seo',
      employeeType: 'seo',
      title: 'SEO keyword & meta plan',
      description: 'Keyword research, meta title/description, headings, and on-page recommendations',
      dependsOn: ['research'],
      approvalRequired: false,
    },
    {
      id: 'writer',
      employeeType: 'writer',
      title: 'Write blog post',
      description: 'Write SEO-optimized blog post using research and keyword plan',
      input: { contentType: 'blog' },
      dependsOn: ['research', 'seo'],
      approvalRequired: false,
    },
    {
      id: 'reviewer',
      employeeType: 'reviewer',
      title: 'Review and optimize',
      description: 'Grammar check, SEO audit, readability score, fact-check',
      dependsOn: ['writer'],
      approvalRequired: false,
    },
    {
      id: 'image',
      employeeType: 'image',
      title: 'Create featured image',
      description: 'Generate blog thumbnail and in-article illustrations',
      input: { imageType: 'illustration', count: 3 },
      dependsOn: ['writer'],
      approvalRequired: false,
    },
    {
      id: 'qa',
      employeeType: 'qa',
      title: 'Compliance & brand-safety check',
      description: 'Plagiarism, copyright, brand-safety, and policy gate before publishing',
      dependsOn: ['reviewer'],
      approvalRequired: false,
    },
    {
      id: 'publisher',
      employeeType: 'publisher',
      title: 'Publish to blog',
      description: 'Format and publish blog post with metadata and images',
      dependsOn: ['qa', 'image'],
      approvalRequired: true,
    },
    {
      id: 'social',
      employeeType: 'social',
      title: 'Distribute on social',
      description: 'Draft platform-native promo posts and a posting schedule',
      dependsOn: ['publisher'],
      approvalRequired: false,
      optional: true,
    },
  ],
});
