import { WorkflowRegistry } from '../workflow.registry';

WorkflowRegistry.register({
  id: 'youtube-video',
  name: 'YouTube Video Production',
  description: 'Full YouTube video production pipeline: research, script writing, review, voiceover, images, video assembly, editing, and publishing',
  version: '1.0.0',
  category: 'media',
  estimatedDurationMinutes: 45,
  tags: ['youtube', 'video', 'content', 'social-media'],
  defaultInput: {
    tone: 'professional',
    videoStyle: 'educational',
    platforms: ['youtube'],
  },
  steps: [
    {
      id: 'research',
      employeeType: 'research',
      title: 'Research topic',
      description: 'Gather information, verify sources, and prepare research data',
      dependsOn: [],
      approvalRequired: false,
    },
    {
      id: 'planning',
      employeeType: 'planning',
      title: 'Plan video structure',
      description: 'Create video outline and scene breakdown',
      dependsOn: ['research'],
      approvalRequired: false,
    },
    {
      id: 'writer',
      employeeType: 'writer',
      title: 'Write video script',
      description: 'Write engaging script with hook, main content, and call-to-action',
      input: { contentType: 'script' },
      dependsOn: ['planning'],
      approvalRequired: false,
    },
    {
      id: 'reviewer',
      employeeType: 'reviewer',
      title: 'Review script',
      description: 'Fact-check, grammar check, SEO optimization, quality scoring',
      dependsOn: ['writer'],
      approvalRequired: true,
    },
    {
      id: 'voice',
      employeeType: 'voice',
      title: 'Generate voiceover',
      description: 'Convert script into narration with timing',
      dependsOn: ['reviewer'],
      approvalRequired: false,
    },
    {
      id: 'image',
      employeeType: 'image',
      title: 'Generate thumbnails and visuals',
      description: 'Create eye-catching thumbnail and scene illustrations',
      input: { imageType: 'thumbnail' },
      dependsOn: ['writer'],
      approvalRequired: false,
    },
    {
      id: 'video',
      employeeType: 'video',
      title: 'Assemble video scenes',
      description: 'Combine voiceover, visuals, and create video production plan',
      dependsOn: ['voice', 'image'],
      approvalRequired: false,
    },
    {
      id: 'editor',
      employeeType: 'editor',
      title: 'Edit final video',
      description: 'Add transitions, subtitles, background music, sync audio',
      dependsOn: ['video'],
      approvalRequired: false,
    },
    {
      id: 'publisher',
      employeeType: 'publisher',
      title: 'Publish to YouTube',
      description: 'Upload video with optimized title, description, and tags',
      input: { platforms: ['youtube'] },
      dependsOn: ['editor'],
      approvalRequired: true,
    },
  ],
});
