import { WorkflowRegistry } from '../workflow.registry';

WorkflowRegistry.register({
  id: 'youtube-video',
  name: 'YouTube Video Production',
  description: 'Full YouTube pipeline: strategy, research, SEO, script, review, voiceover, design, images, video assembly, editing, compliance, publishing, and distribution',
  version: '1.1.0',
  category: 'media',
  estimatedDurationMinutes: 50,
  tags: ['youtube', 'video', 'content', 'social-media'],
  defaultInput: {
    tone: 'professional',
    videoStyle: 'educational',
    platforms: ['youtube'],
  },
  steps: [
    {
      id: 'strategist',
      employeeType: 'strategist',
      title: 'Plan content strategy',
      description: 'Detect trends and select a high-opportunity video topic and audience',
      dependsOn: [],
      approvalRequired: false,
      optional: true,
    },
    {
      id: 'research',
      employeeType: 'research',
      title: 'Research topic',
      description: 'Gather information, verify sources, and prepare research data',
      dependsOn: ['strategist'],
      approvalRequired: false,
    },
    {
      id: 'seo',
      employeeType: 'seo',
      title: 'SEO title & tags plan',
      description: 'Keyword research, optimized title, description, and tags for discoverability',
      dependsOn: ['research'],
      approvalRequired: false,
    },
    {
      id: 'planning',
      employeeType: 'planning',
      title: 'Plan video structure',
      description: 'Create video outline and scene breakdown',
      dependsOn: ['research'],
      approvalRequired: false,
    },
    {
      id: 'writer',
      employeeType: 'writer',
      title: 'Write video script',
      description: 'Write engaging script with hook, main content, and call-to-action',
      input: { contentType: 'script' },
      dependsOn: ['planning', 'seo'],
      approvalRequired: false,
    },
    {
      id: 'reviewer',
      employeeType: 'reviewer',
      title: 'Review script',
      description: 'Fact-check, grammar check, SEO optimization, quality scoring',
      dependsOn: ['writer'],
      approvalRequired: true,
    },
    {
      id: 'voice',
      employeeType: 'voice',
      title: 'Generate voiceover',
      description: 'Convert script into narration with timing',
      dependsOn: ['reviewer'],
      approvalRequired: false,
    },
    {
      id: 'designer',
      employeeType: 'designer',
      title: 'Design thumbnail & visuals brief',
      description: 'Create brand-consistent thumbnail concepts and image-generation prompts',
      dependsOn: ['writer'],
      approvalRequired: false,
    },
    {
      id: 'image',
      employeeType: 'image',
      title: 'Generate thumbnails and visuals',
      description: 'Create eye-catching thumbnail and scene illustrations from the design brief',
      input: { imageType: 'thumbnail' },
      dependsOn: ['designer'],
      approvalRequired: false,
    },
    {
      id: 'video',
      employeeType: 'video',
      title: 'Assemble video scenes',
      description: 'Combine voiceover, visuals, and create video production plan',
      dependsOn: ['voice', 'image'],
      approvalRequired: false,
    },
    {
      id: 'editor',
      employeeType: 'editor',
      title: 'Edit final video',
      description: 'Add transitions, subtitles, background music, sync audio',
      dependsOn: ['video'],
      approvalRequired: false,
    },
    {
      id: 'qa',
      employeeType: 'qa',
      title: 'Compliance & brand-safety check',
      description: 'Copyright, brand-safety, and platform-policy gate before publishing',
      dependsOn: ['editor'],
      approvalRequired: false,
    },
    {
      id: 'publisher',
      employeeType: 'publisher',
      title: 'Publish to YouTube',
      description: 'Upload video with optimized title, description, and tags',
      input: { platforms: ['youtube'] },
      dependsOn: ['qa'],
      approvalRequired: true,
    },
    {
      id: 'social',
      employeeType: 'social',
      title: 'Cross-promote on social',
      description: 'Draft platform-native promo posts and a posting schedule',
      dependsOn: ['publisher'],
      approvalRequired: false,
      optional: true,
    },
  ],
});
